---
- name: test if operating eviroment suitable for role
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version|int > 17
    quiet: true
