---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nvim_ppa_ubuntu-jammy
    dockerfile: ../resources/Dockerfile.j2
    image: ubuntu-jammy
    privileged: true
    command: sleep infinity
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
